import React from 'react'
import moment from 'moment';
function Report({ setReportVisible, reportVisible, session }) {


    return (
        <div className={`absolute w-full bg-black/30 h-full top-0 left-0 pt-10 ${!reportVisible ? 'hidden' : ''}`}>
            <div className="flex justify-center items-center max-md:items-start ">
                <div className="bg-white rounded-lg py-5 px-8 w-1/2 max-md:w-full max-lg:w-3/4 mx-4">
                    <div className=" flex justify-between items-center mb-4">
                        <h1 className='text-blue-500 font-semibold text-2xl w-[95%]'>Medical AI Voice Agent Report</h1>
                        <button className="font-semibold text-xl hover:bg-gray-200 p-2 rounded-md hover:cursor-pointer" onClick={() => setReportVisible(false)}>X</button>
                    </div>
                    <div className="mb-3">
                        <h1 className='text-2xl text-start text-blue-500 font-semibold py-2 border-b-2 border-blue-500'>Session Info</h1>
                        <div className="flex justify-start items-center py-2 gap-3">
                            <div className="text-lg text-gray-600 w-1/2 text-start"><span className='font-semibold text-gray-700'>Doctor : </span>{session.doctor.name}</div>
                            <div className="text-lg text-gray-600 w-1/3 text-start"><span className='font-semibold text-gray-700'>User : </span>{session.session.report.user}</div>
                        </div>
                        <div className="flex justify-start items-center py-2 gap-3">
                            <div className="text-lg text-gray-600 w-1/2 text-start"><span className='font-semibold text-gray-700'>Consulted On : </span>{moment(new Date(session.session.report.timestamp)).format('MMMM Do YYYY, h:mm:ss a')}</div>
                            <div className="text-lg text-gray-600 w-1/3 text-start"><span className='font-semibold text-gray-700'>Specialization : </span>{session.doctor.specialization}</div>
                        </div>
                    </div>
                    <div className="mb-3">
                        <h1 className='text-2xl text-start text-blue-500 font-semibold py-2 border-b-2 border-blue-500'>Chief Complaint</h1>
                        <div className="text-lg text-gray-600 w-full text-start py-2">{session.session.report.chiefComplaint}</div>
                    </div>
                    <div className="mb-3">
                        <h1 className='text-2xl text-start text-blue-500 font-semibold py-2 border-b-2 border-blue-500'>Summary</h1>
                        <div className="text-lg text-gray-600 w-full text-start py-2">{session.session.report.summary}</div>
                    </div>
                    <div className="mb-3">
                        <h1 className='text-2xl text-start text-blue-500 font-semibold py-2 border-b-2 border-blue-500'>Symptoms</h1>
                        <div className="text-lg text-gray-600 w-full text-start py-2 px-5">
                            {session.session.report.symptoms?.map((sy, index) => (
                                <li key={index} className='text-lg text-gray-600 w-full text-start'>{sy}</li>
                            ))}
                        </div>
                    </div>
                    <div className="mb-3">
                        <h1 className='text-2xl text-start text-blue-500 font-semibold py-2 border-b-2 border-blue-500'>Recommendations</h1>
                        <div className="text-lg text-gray-600 w-full text-start py-2 px-5">
                            {session.session.report.recommendations?.map((sy, index) => (
                                <li key={index} className='text-lg text-gray-600 w-full text-start'>{sy}</li>
                            ))}
                        </div>
                    </div>

                    <div className="mt-5 border-t-2 border-gray-300 pt-3">
                        <div className="text-gray-500 w-full text-center py-2">
                            This report was generated by an AI Medical Assistant for informational purposes only.
                        </div>
                    </div>

                </div>
            </div>
        </div>
    )
}

export default Report